---
alwaysontop: 0
opacity: 0.9
win_ssh_key: 'c:\ssh\keys\private_key.ppk'
sessions:
- - site: development
  - - host: v00server1t
      desc: test server 1
      users:
        - [user: 'dwebuser']
        - [user: 'root']
        - [user: 'dusername']
    - host: v00server2t
      desc: test server 2
      users:
        - [user: 'dwebuser']
        - [user: 'root']
        - [user: 'dusername']
- - site: alpha
  - - host: v01server1t
      desc: alpha server 1
      users:
        - [user: 'awebuser']
        - [user: 'root']
        - [user: 'ausername']
    - host: v01server2t
      desc: alpha server 2
      users:
        - [user: 'awebuser']
        - [user: 'root']
        - [user: 'ausername']
- - site: beta
  - - host: v02server1t
      desc: beta server 1
      users:
        - [user: 'bwebuser']
        - [user: 'root']
        - [user: 'busername']
    - host: v02server2t
      desc: beta server 2
      users:
        - [user: 'bwebuser']
        - [user: 'root']
        - [user: 'busername']
- - site: production
  - - host: v02server1
      desc: production server 1
      users:
        - [user: 'pwebuser']
        - [user: 'root']
        - [user: 'pusername']
    - host: v02server2
      desc: production server 2
      users:
        - [user: 'pwebuser']
        - [user: 'root']
        - [user: 'pusername']
